using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Xml.Linq;
using Palmmedia.ReportGenerator.Core.Logging;
using Palmmedia.ReportGenerator.Core.Properties;

namespace Palmmedia.ReportGenerator.Core.Parser.Preprocessing
{
    /// <summary>
    /// Preprocessor for Clover reports.
    /// </summary>
    internal class CloverReportPreprocessor
    {
        /// <summary>
        /// The Logger.
        /// </summary>
        private static readonly ILogger Logger = LoggerFactory.GetLogger(typeof(CloverReportPreprocessor));

        /// <summary>
        /// The source directories.
        /// </summary>
        private readonly IReadOnlyList<string> sourceDirectories;

        /// <summary>
        /// Initializes a new instance of the <see cref="CloverReportPreprocessor"/> class.
        /// </summary>
        /// <param name="sourceDirectories">The source directories.</param>
        internal CloverReportPreprocessor(IEnumerable<string> sourceDirectories)
        {
            if (sourceDirectories == null)
            {
                throw new ArgumentNullException(nameof(sourceDirectories));
            }

            this.sourceDirectories = sourceDirectories.ToList();
        }

        /// <summary>
        /// Executes the preprocessing of the report.
        /// </summary>
        /// <param name="report">The report.</param>
        internal void Execute(XContainer report)
        {
            // Remove namespace declaration if it exists (required to support coverage files generated by https://github.com/jsargiot/visual-coverage)
            report.Descendants()
               .Attributes()
               .Where(x => x.IsNamespaceDeclaration)
               .Remove();

            foreach (var elem in report.Descendants())
            {
                elem.Name = elem.Name.LocalName;
            }

            var files = report.Descendants("package").Elements("file").ToArray();

            // Fix attribute name (required to support coverage files generated by PhpUnit)
            foreach (var file in files)
            {
                var nameAttribute = file.Attribute("name");
                if (nameAttribute != null && file.Attribute("path") == null)
                {
                    file.Add(new XAttribute("path", nameAttribute.Value));
                }
            }

            if (this.sourceDirectories.Count == 0)
            {
                foreach (var file in files)
                {
                    if (!Path.IsPathRooted(file.Attribute("path").Value))
                    {
                        Logger.Warn("  " + string.Format(Resources.NoSourceDirectories, "Clover"));
                        return;
                    }
                }

                return;
            }

            foreach (var file in files)
            {
                var pathAttribute = file.Attribute("path");

                pathAttribute.Value = this.GetFullFilePath(pathAttribute.Value);
            }
        }

        /// <summary>
        /// Gets the full path of the file.
        /// </summary>
        /// <param name="initialPath">The initial path of the file.</param>
        /// <returns>The full path of the file.</returns>
        private string GetFullFilePath(string initialPath)
        {
            if (!Path.IsPathRooted(initialPath))
            {
                foreach (var sourceDirectory in this.sourceDirectories)
                {
                    string path = Path.Combine(sourceDirectory, initialPath);

                    if (File.Exists(path))
                    {
                        return path;
                    }
                }
            }

            return initialPath;
        }
    }
}
