//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Palmmedia.ReportGenerator.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Help {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Help() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Palmmedia.ReportGenerator.Core.Properties.Help", typeof(Help).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default values:.
        /// </summary>
        internal static string DefaultValues {
            get {
                return ResourceManager.GetString("DefaultValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examples:.
        /// </summary>
        internal static string Examples {
            get {
                return ResourceManager.GetString("Examples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explanations:.
        /// </summary>
        internal static string Explanations {
            get {
                return ResourceManager.GetString("Explanations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly filters:   Optional list of assemblies that should be included or excluded in the report..
        /// </summary>
        internal static string Explanations_AssemblyFilters {
            get {
                return ResourceManager.GetString("Explanations_AssemblyFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class filters:      Optional list of classes that should be included or excluded in the report..
        /// </summary>
        internal static string Explanations_ClassFilters {
            get {
                return ResourceManager.GetString("Explanations_ClassFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File filters:       Optional list of files that should be included or excluded in the report..
        /// </summary>
        internal static string Explanations_FileFilters {
            get {
                return ResourceManager.GetString("Explanations_FileFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                     Exclusion filters take precedence over inclusion filters. Wildcards are allowed..
        /// </summary>
        internal static string Explanations_FiltersCommon {
            get {
                return ResourceManager.GetString("Explanations_FiltersCommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History directory:  Optional directory for storing persistent coverage information..
        /// </summary>
        internal static string Explanations_HistoryDirectory {
            get {
                return ResourceManager.GetString("Explanations_HistoryDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License:            Optional license for PRO version. Get your license here: https://reportgenerator.io/pro.
        /// </summary>
        internal static string Explanations_License {
            get {
                return ResourceManager.GetString("Explanations_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins:            Optional plugin files for custom reports or custom history storage (separated by semicolon)..
        /// </summary>
        internal static string Explanations_Plugins {
            get {
                return ResourceManager.GetString("Explanations_Plugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports:            The coverage reports that should be parsed (separated by semicolon). Globbing is supported..
        /// </summary>
        internal static string Explanations_Reports {
            get {
                return ResourceManager.GetString("Explanations_Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report types:       The output formats and scope (separated by semicolon)..
        /// </summary>
        internal static string Explanations_ReportTypes {
            get {
                return ResourceManager.GetString("Explanations_ReportTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risk hotspot assembly filters: Optional list of assemblies that should be included or excluded in the risk hotspots..
        /// </summary>
        internal static string Explanations_RiskHotspotAssemblyFilters {
            get {
                return ResourceManager.GetString("Explanations_RiskHotspotAssemblyFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risk hotspot class filters:    Optional list of classes that should be included or excluded in the risk hotspots..
        /// </summary>
        internal static string Explanations_RiskHotspotClassFilters {
            get {
                return ResourceManager.GetString("Explanations_RiskHotspotClassFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source directories: Optional directories which contain the corresponding source code (separated by semicolon)..
        /// </summary>
        internal static string Explanations_SourceDirectories {
            get {
                return ResourceManager.GetString("Explanations_SourceDirectories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                     The source directories are used if coverage report contains classes without path information.
        ///                        Globbing is not supported..
        /// </summary>
        internal static string Explanations_SourceDirectories2 {
            get {
                return ResourceManager.GetString("Explanations_SourceDirectories2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag:                Optional tag or build version..
        /// </summary>
        internal static string Explanations_Tag {
            get {
                return ResourceManager.GetString("Explanations_Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target directory:   The directory where the generated report should be saved..
        /// </summary>
        internal static string Explanations_TargetDirectory {
            get {
                return ResourceManager.GetString("Explanations_TargetDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title:              Optional title..
        /// </summary>
        internal static string Explanations_Title {
            get {
                return ResourceManager.GetString("Explanations_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbosity:          The verbosity level of the log messages..
        /// </summary>
        internal static string Explanations_Verbosity {
            get {
                return ResourceManager.GetString("Explanations_Verbosity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                     Can be used in future reports to show coverage evolution..
        /// </summary>
        internal static string Explanations7 {
            get {
                return ResourceManager.GetString("Explanations7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters:.
        /// </summary>
        internal static string Parameters {
            get {
                return ResourceManager.GetString("Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [[&quot;]-assemblyfilters:&lt;(+|-)filter&gt;[;&lt;(+|-)filter&gt;][;&lt;(+|-)filter&gt;][&quot;]].
        /// </summary>
        internal static string Parameters_AssemblyFilters {
            get {
                return ResourceManager.GetString("Parameters_AssemblyFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [[&quot;]-classfilters:&lt;(+|-)filter&gt;[;&lt;(+|-)filter&gt;][;&lt;(+|-)filter&gt;][&quot;]].
        /// </summary>
        internal static string Parameters_ClassFilters {
            get {
                return ResourceManager.GetString("Parameters_ClassFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [[&quot;]-filefilters:&lt;(+|-)filter&gt;[;&lt;(+|-)filter&gt;][;&lt;(+|-)filter&gt;][&quot;]].
        /// </summary>
        internal static string Parameters_FileFilters {
            get {
                return ResourceManager.GetString("Parameters_FileFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [[&quot;]-historydir:&lt;history directory&gt;[&quot;]].
        /// </summary>
        internal static string Parameters_HistoryDirectory {
            get {
                return ResourceManager.GetString("Parameters_HistoryDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [[&quot;]-license:&lt;license&gt;[&quot;]].
        /// </summary>
        internal static string Parameters_License {
            get {
                return ResourceManager.GetString("Parameters_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [[&quot;]-plugins:&lt;plugin&gt;[;&lt;plugin&gt;][;&lt;plugin&gt;][&quot;]].
        /// </summary>
        internal static string Parameters_Plugins {
            get {
                return ResourceManager.GetString("Parameters_Plugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [&quot;]-reports:&lt;report&gt;[;&lt;report&gt;][;&lt;report&gt;][&quot;].
        /// </summary>
        internal static string Parameters_Reports {
            get {
                return ResourceManager.GetString("Parameters_Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [[&quot;]-reporttypes:&lt;{0}&gt;[;&lt;{0}&gt;][&quot;]]&quot;.
        /// </summary>
        internal static string Parameters_ReportTypes {
            get {
                return ResourceManager.GetString("Parameters_ReportTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [[&quot;]-riskhotspotassemblyfilters:&lt;(+|-)filter&gt;[;&lt;(+|-)filter&gt;][;&lt;(+|-)filter&gt;][&quot;]].
        /// </summary>
        internal static string Parameters_RiskHotspotAssemblyFilters {
            get {
                return ResourceManager.GetString("Parameters_RiskHotspotAssemblyFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [[&quot;]-riskhotspotclassfilters:&lt;(+|-)filter&gt;[;&lt;(+|-)filter&gt;][;&lt;(+|-)filter&gt;][&quot;]].
        /// </summary>
        internal static string Parameters_RiskHotspotClassFilters {
            get {
                return ResourceManager.GetString("Parameters_RiskHotspotClassFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [[&quot;]-sourcedirs:&lt;directory&gt;[;&lt;directory&gt;][;&lt;directory&gt;][&quot;]].
        /// </summary>
        internal static string Parameters_SourceDirectories {
            get {
                return ResourceManager.GetString("Parameters_SourceDirectories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [[&quot;]-tag:&lt;tag&gt;[&quot;]].
        /// </summary>
        internal static string Parameters_Tag {
            get {
                return ResourceManager.GetString("Parameters_Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [&quot;]-targetdir:&lt;target directory&gt;[&quot;].
        /// </summary>
        internal static string Parameters_TargetDirectory {
            get {
                return ResourceManager.GetString("Parameters_TargetDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [[&quot;]-title:&lt;title&gt;[&quot;]].
        /// </summary>
        internal static string Parameters_Title {
            get {
                return ResourceManager.GetString("Parameters_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [[&quot;]-verbosity:&lt;{0}&gt;[&quot;]].
        /// </summary>
        internal static string Parameters_Verbosity {
            get {
                return ResourceManager.GetString("Parameters_Verbosity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                     Values: {0}.
        /// </summary>
        internal static string ReportTypeValues {
            get {
                return ResourceManager.GetString("ReportTypeValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                     Values: {0}.
        /// </summary>
        internal static string VerbosityValues {
            get {
                return ResourceManager.GetString("VerbosityValues", resourceCulture);
            }
        }
    }
}
