//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Palmmedia.ReportGenerator.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReportResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReportResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Palmmedia.ReportGenerator.Core.Properties.ReportResources", typeof(ReportResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All changes.
        /// </summary>
        public static string AllChanges {
            get {
                return ResourceManager.GetString("AllChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assemblies.
        /// </summary>
        public static string Assemblies {
            get {
                return ResourceManager.GetString("Assemblies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assemblies:.
        /// </summary>
        public static string Assemblies2 {
            get {
                return ResourceManager.GetString("Assemblies2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly:.
        /// </summary>
        public static string Assembly {
            get {
                return ResourceManager.GetString("Assembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly.
        /// </summary>
        public static string Assembly2 {
            get {
                return ResourceManager.GetString("Assembly2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocks covered.
        /// </summary>
        public static string BlocksCovered {
            get {
                return ResourceManager.GetString("BlocksCovered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocks not covered.
        /// </summary>
        public static string BlocksNotCovered {
            get {
                return ResourceManager.GetString("BlocksNotCovered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        public static string Branch {
            get {
                return ResourceManager.GetString("Branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch coverage.
        /// </summary>
        public static string BranchCoverage {
            get {
                return ResourceManager.GetString("BranchCoverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch coverage:.
        /// </summary>
        public static string BranchCoverage2 {
            get {
                return ResourceManager.GetString("BranchCoverage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch coverage: Decrease only.
        /// </summary>
        public static string BranchCoverageDecreaseOnly {
            get {
                return ResourceManager.GetString("BranchCoverageDecreaseOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch coverage: Increase only.
        /// </summary>
        public static string BranchCoverageIncreaseOnly {
            get {
                return ResourceManager.GetString("BranchCoverageIncreaseOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branches.
        /// </summary>
        public static string Branches {
            get {
                return ResourceManager.GetString("Branches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By assembly.
        /// </summary>
        public static string ByAssembly {
            get {
                return ResourceManager.GetString("ByAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By namespace, Level:.
        /// </summary>
        public static string ByNamespace {
            get {
                return ResourceManager.GetString("ByNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class:.
        /// </summary>
        public static string Class {
            get {
                return ResourceManager.GetString("Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        public static string Class2 {
            get {
                return ResourceManager.GetString("Class2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classes:.
        /// </summary>
        public static string Classes {
            get {
                return ResourceManager.GetString("Classes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code coverage.
        /// </summary>
        public static string CodeCoverage {
            get {
                return ResourceManager.GetString("CodeCoverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method coverage: Decrease only.
        /// </summary>
        public static string CodeElementCoverageDecreaseOnly {
            get {
                return ResourceManager.GetString("CodeElementCoverageDecreaseOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method coverage: Increase only.
        /// </summary>
        public static string CodeElementCoverageIncreaseOnly {
            get {
                return ResourceManager.GetString("CodeElementCoverageIncreaseOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method coverage.
        /// </summary>
        public static string CodeElementCoverageQuota {
            get {
                return ResourceManager.GetString("CodeElementCoverageQuota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method coverage:.
        /// </summary>
        public static string CodeElementCoverageQuota2 {
            get {
                return ResourceManager.GetString("CodeElementCoverageQuota2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse all.
        /// </summary>
        public static string CollapseAll {
            get {
                return ResourceManager.GetString("CollapseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare with:.
        /// </summary>
        public static string CompareHistory {
            get {
                return ResourceManager.GetString("CompareHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coverable.
        /// </summary>
        public static string Coverable {
            get {
                return ResourceManager.GetString("Coverable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coverable lines:.
        /// </summary>
        public static string CoverableLines {
            get {
                return ResourceManager.GetString("CoverableLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line coverage.
        /// </summary>
        public static string Coverage {
            get {
                return ResourceManager.GetString("Coverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line coverage:.
        /// </summary>
        public static string Coverage2 {
            get {
                return ResourceManager.GetString("Coverage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coverage.
        /// </summary>
        public static string Coverage3 {
            get {
                return ResourceManager.GetString("Coverage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coverage date:.
        /// </summary>
        public static string CoverageDate {
            get {
                return ResourceManager.GetString("CoverageDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coverage Report.
        /// </summary>
        public static string CoverageReport {
            get {
                return ResourceManager.GetString("CoverageReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Covered ({0} visits{1}).
        /// </summary>
        public static string CoverageTooltip_Covered {
            get {
                return ResourceManager.GetString("CoverageTooltip_Covered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not coverable.
        /// </summary>
        public static string CoverageTooltip_NotCoverable {
            get {
                return ResourceManager.GetString("CoverageTooltip_NotCoverable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not covered ({0} visits{1}).
        /// </summary>
        public static string CoverageTooltip_NotCovered {
            get {
                return ResourceManager.GetString("CoverageTooltip_NotCovered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partially covered ({0} visits{1}).
        /// </summary>
        public static string CoverageTooltip_PartiallyCovered {
            get {
                return ResourceManager.GetString("CoverageTooltip_PartiallyCovered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coverage types.
        /// </summary>
        public static string CoverageTypes {
            get {
                return ResourceManager.GetString("CoverageTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Covered.
        /// </summary>
        public static string Covered {
            get {
                return ResourceManager.GetString("Covered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1} branches are covered.
        /// </summary>
        public static string CoveredBranches {
            get {
                return ResourceManager.GetString("CoveredBranches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Covered branches:.
        /// </summary>
        public static string CoveredBranches2 {
            get {
                return ResourceManager.GetString("CoveredBranches2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Covered methods:.
        /// </summary>
        public static string CoveredCodeElements {
            get {
                return ResourceManager.GetString("CoveredCodeElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Covered lines:.
        /// </summary>
        public static string CoveredLines {
            get {
                return ResourceManager.GetString("CoveredLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crap Score.
        /// </summary>
        public static string CrapScore {
            get {
                return ResourceManager.GetString("CrapScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        public static string Current {
            get {
                return ResourceManager.GetString("Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyclomatic complexity.
        /// </summary>
        public static string CyclomaticComplexity {
            get {
                return ResourceManager.GetString("CyclomaticComplexity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delta.
        /// </summary>
        public static string Delta {
            get {
                return ResourceManager.GetString("Delta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delta Summary.
        /// </summary>
        public static string DeltaSummary {
            get {
                return ResourceManager.GetString("DeltaSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand all.
        /// </summary>
        public static string ExpandAll {
            get {
                return ResourceManager.GetString("ExpandAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File(s).
        /// </summary>
        public static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files:.
        /// </summary>
        public static string Files2 {
            get {
                return ResourceManager.GetString("Files2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File(s):.
        /// </summary>
        public static string Files3 {
            get {
                return ResourceManager.GetString("Files3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter:.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full method coverage: Decrease only.
        /// </summary>
        public static string FullCodeElementCoverageDecreaseOnly {
            get {
                return ResourceManager.GetString("FullCodeElementCoverageDecreaseOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full method coverage: Increase only.
        /// </summary>
        public static string FullCodeElementCoverageIncreaseOnly {
            get {
                return ResourceManager.GetString("FullCodeElementCoverageIncreaseOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full method coverage.
        /// </summary>
        public static string FullCodeElementCoverageQuota {
            get {
                return ResourceManager.GetString("FullCodeElementCoverageQuota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full method coverage:.
        /// </summary>
        public static string FullCodeElementCoverageQuota2 {
            get {
                return ResourceManager.GetString("FullCodeElementCoverageQuota2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fully covered methods:.
        /// </summary>
        public static string FullCoveredCodeElements {
            get {
                return ResourceManager.GetString("FullCoveredCodeElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full method.
        /// </summary>
        public static string FullMethod {
            get {
                return ResourceManager.GetString("FullMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated by:.
        /// </summary>
        public static string GeneratedBy {
            get {
                return ResourceManager.GetString("GeneratedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated on:.
        /// </summary>
        public static string GeneratedOn {
            get {
                return ResourceManager.GetString("GeneratedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grouping:.
        /// </summary>
        public static string Grouping {
            get {
                return ResourceManager.GetString("Grouping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coverage history.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        public static string Line {
            get {
                return ResourceManager.GetString("Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line coverage: Decrease only.
        /// </summary>
        public static string LineCoverageDecreaseOnly {
            get {
                return ResourceManager.GetString("LineCoverageDecreaseOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line coverage: Increase only.
        /// </summary>
        public static string LineCoverageIncreaseOnly {
            get {
                return ResourceManager.GetString("LineCoverageIncreaseOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method.
        /// </summary>
        public static string Method {
            get {
                return ResourceManager.GetString("Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade to PRO version.
        /// </summary>
        public static string MethodCoverageProButton {
            get {
                return ResourceManager.GetString("MethodCoverageProButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature is only available for sponsors.
        /// </summary>
        public static string MethodCoverageProVersion {
            get {
                return ResourceManager.GetString("MethodCoverageProVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Methods/Properties.
        /// </summary>
        public static string MethodsProperties {
            get {
                return ResourceManager.GetString("MethodsProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metrics.
        /// </summary>
        public static string Metrics {
            get {
                return ResourceManager.GetString("Metrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No assemblies have been covered..
        /// </summary>
        public static string NoCoveredAssemblies {
            get {
                return ResourceManager.GetString("NoCoveredAssemblies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No files found. This usually happens if a file isn&apos;t covered by a test or the class does not contain any sequence points (e.g. a class that only contains auto properties)..
        /// </summary>
        public static string NoFilesFound {
            get {
                return ResourceManager.GetString("NoFilesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No grouping.
        /// </summary>
        public static string NoGrouping {
            get {
                return ResourceManager.GetString("NoGrouping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No risk hotspots found..
        /// </summary>
        public static string NoRiskHotspots {
            get {
                return ResourceManager.GetString("NoRiskHotspots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        public static string NotAvailable {
            get {
                return ResourceManager.GetString("NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NPath complexity.
        /// </summary>
        public static string NPathComplexity {
            get {
                return ResourceManager.GetString("NPathComplexity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        public static string Of {
            get {
                return ResourceManager.GetString("Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parser:.
        /// </summary>
        public static string Parser {
            get {
                return ResourceManager.GetString("Parser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage.
        /// </summary>
        public static string Percentage {
            get {
                return ResourceManager.GetString("Percentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risk Hotspots.
        /// </summary>
        public static string RiskHotspots {
            get {
                return ResourceManager.GetString("RiskHotspots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select coverage types.
        /// </summary>
        public static string SelectCoverageTypes {
            get {
                return ResourceManager.GetString("SelectCoverageTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select coverage types &amp; metrics.
        /// </summary>
        public static string SelectCoverageTypesAndMetrics {
            get {
                return ResourceManager.GetString("SelectCoverageTypesAndMetrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence coverage.
        /// </summary>
        public static string SequenceCoverage {
            get {
                return ResourceManager.GetString("SequenceCoverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sponsor.
        /// </summary>
        public static string Sponsor {
            get {
                return ResourceManager.GetString("Sponsor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Become a sponsor.
        /// </summary>
        public static string SponsorTooltip {
            get {
                return ResourceManager.GetString("SponsorTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Star.
        /// </summary>
        public static string Star {
            get {
                return ResourceManager.GetString("Star", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Star on GitHub.
        /// </summary>
        public static string StarTooltip {
            get {
                return ResourceManager.GetString("StarTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag:.
        /// </summary>
        public static string Tag {
            get {
                return ResourceManager.GetString("Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coverage by test methods.
        /// </summary>
        public static string Testmethods {
            get {
                return ResourceManager.GetString("Testmethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top:.
        /// </summary>
        public static string Top {
            get {
                return ResourceManager.GetString("Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total branches:.
        /// </summary>
        public static string TotalBranches {
            get {
                return ResourceManager.GetString("TotalBranches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total methods:.
        /// </summary>
        public static string TotalCodeElements {
            get {
                return ResourceManager.GetString("TotalCodeElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total lines:.
        /// </summary>
        public static string TotalLines {
            get {
                return ResourceManager.GetString("TotalLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncovered.
        /// </summary>
        public static string Uncovered {
            get {
                return ResourceManager.GetString("Uncovered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncovered lines:.
        /// </summary>
        public static string UncoveredLines {
            get {
                return ResourceManager.GetString("UncoveredLines", resourceCulture);
            }
        }
    }
}
