//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Palmmedia.ReportGenerator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Palmmedia.ReportGenerator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added coverage information of {0}/{1} auto properties.
        /// </summary>
        internal static string AddedCoverageInformationOfProperties {
            get {
                return ResourceManager.GetString("AddedCoverageInformationOfProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added coverage information of {0}/{1} auto properties to module &apos;{2}&apos;.
        /// </summary>
        internal static string AddedCoverageInformationOfPropertiesOpenCover {
            get {
                return ResourceManager.GetString("AddedCoverageInformationOfPropertiesOpenCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added coverage information of {0}/{1} unexecuted methods.
        /// </summary>
        internal static string AddedCoverageInformationUnexecutedMethods {
            get {
                return ResourceManager.GetString("AddedCoverageInformationUnexecutedMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyzing {0} classes.
        /// </summary>
        internal static string AnalyzingClasses {
            get {
                return ResourceManager.GetString("AnalyzingClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating history report.
        /// </summary>
        internal static string CreatingHistoryReport {
            get {
                return ResourceManager.GetString("CreatingHistoryReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating report {0}/{1} (Assembly: {2}, Class: {3}).
        /// </summary>
        internal static string CreatingReport {
            get {
                return ResourceManager.GetString("CreatingReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating summary.
        /// </summary>
        internal static string CreatingSummary {
            get {
                return ResourceManager.GetString("CreatingSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSS &apos;{0}&apos; could not be saved: {1}.
        /// </summary>
        internal static string CssNotSaved {
            get {
                return ResourceManager.GetString("CssNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Assembly: {0}.
        /// </summary>
        internal static string CurrentAssembly {
            get {
                return ResourceManager.GetString("CurrentAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default report builder for report type &apos;{0}&apos; was replaced..
        /// </summary>
        internal static string DefaultReportBuilderReplaced {
            get {
                return ResourceManager.GetString("DefaultReportBuilderReplaced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during reading file &apos;{0}&apos;: {1}.
        /// </summary>
        internal static string ErrorDuringReadingFile {
            get {
                return ResourceManager.GetString("ErrorDuringReadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during reading historic report &apos;{0}&apos;: {1}.
        /// </summary>
        internal static string ErrorDuringReadingHistoricReport {
            get {
                return ResourceManager.GetString("ErrorDuringReadingHistoricReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during reading historic reports: {0}.
        /// </summary>
        internal static string ErrorDuringReadingHistoricReports {
            get {
                return ResourceManager.GetString("ErrorDuringReadingHistoricReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during reading report &apos;{0}&apos;: {1}.
        /// </summary>
        internal static string ErrorDuringReadingReport {
            get {
                return ResourceManager.GetString("ErrorDuringReadingReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during rendering report for class &apos;{0}&apos; (Report type: &apos;{1}&apos;): {2}.
        /// </summary>
        internal static string ErrorDuringRenderingClassReport {
            get {
                return ResourceManager.GetString("ErrorDuringRenderingClassReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during rendering summary report (Report type: &apos;{0}&apos;): {1}.
        /// </summary>
        internal static string ErrorDuringRenderingSummaryReport {
            get {
                return ResourceManager.GetString("ErrorDuringRenderingSummaryReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during saving historic report &apos;{0}&apos;: {1}.
        /// </summary>
        internal static string ErrorDuringSavingHistoricReport {
            get {
                return ResourceManager.GetString("ErrorDuringSavingHistoricReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The report file pattern &apos;{0}&apos; is invalid..
        /// </summary>
        internal static string FailedReportFilePattern {
            get {
                return ResourceManager.GetString("FailedReportFilePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; does not exist (any more)..
        /// </summary>
        internal static string FileDoesNotExist {
            get {
                return ResourceManager.GetString("FileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load file &apos;{0}&apos;. Please unblock all files in installation directory. See https://github.com/danielpalme/ReportGenerator/wiki/FAQ#i-get-a-fileloadexception-when-executing-reportgenerator-how-can-i-fix-this for details..
        /// </summary>
        internal static string FileLoadError {
            get {
                return ResourceManager.GetString("FileLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load file &apos;{0}&apos;. Errors:
        ///{1}.
        /// </summary>
        internal static string FileReflectionLoadError {
            get {
                return ResourceManager.GetString("FileReflectionLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The history directory &apos;{0}&apos; could not be created: {1}.
        /// </summary>
        internal static string HistoryDirectoryCouldNotBeCreated {
            get {
                return ResourceManager.GetString("HistoryDirectoryCouldNotBeCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indexing classes in directory &apos;{0}&apos;.
        /// </summary>
        internal static string IndexingClasses {
            get {
                return ResourceManager.GetString("IndexingClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing report builders for report types: {0}.
        /// </summary>
        internal static string InitializingReportBuilders {
            get {
                return ResourceManager.GetString("InitializingReportBuilders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initiating parser for {0}.
        /// </summary>
        internal static string InitiatingParser {
            get {
                return ResourceManager.GetString("InitiatingParser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The filter &apos;{0}&apos; is invalid. Filters must start with &apos;+&apos; or &apos;-&apos;..
        /// </summary>
        internal static string InvalidFilter {
            get {
                return ResourceManager.GetString("InvalidFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading report &apos;{0}&apos;.
        /// </summary>
        internal static string LoadingReport {
            get {
                return ResourceManager.GetString("LoadingReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No assemblies have been covered..
        /// </summary>
        internal static string NoAssembliesHaveBeenCovered {
            get {
                return ResourceManager.GetString("NoAssembliesHaveBeenCovered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No report files specified..
        /// </summary>
        internal static string NoReportFiles {
            get {
                return ResourceManager.GetString("NoReportFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No target directory specified..
        /// </summary>
        internal static string NoTargetDirectory {
            get {
                return ResourceManager.GetString("NoTargetDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The report file &apos;{0}&apos; does not exist..
        /// </summary>
        internal static string NotExistingReportFile {
            get {
                return ResourceManager.GetString("NotExistingReportFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preprocessing report.
        /// </summary>
        internal static string PreprocessingReport {
            get {
                return ResourceManager.GetString("PreprocessingReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading historic reports.
        /// </summary>
        internal static string ReadingHistoricReports {
            get {
                return ResourceManager.GetString("ReadingHistoricReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report generation took {0:f1} seconds.
        /// </summary>
        internal static string ReportGenerationTook {
            get {
                return ResourceManager.GetString("ReportGenerationTook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Several custom history storages exist. Please ensure that only one custom storage exists..
        /// </summary>
        internal static string SeveralCustomHistoryStorages {
            get {
                return ResourceManager.GetString("SeveralCustomHistoryStorages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Several custom report builders for report type &apos;{0}&apos; exist. This may cause problems if they try to write to the same files/directory..
        /// </summary>
        internal static string SeveralCustomReportBuildersWithSameReportType {
            get {
                return ResourceManager.GetString("SeveralCustomReportBuildersWithSameReportType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source code directory &apos;{0}&apos; does not exist..
        /// </summary>
        internal static string SourceDirectoryDoesNotExist {
            get {
                return ResourceManager.GetString("SourceDirectoryDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target directory &apos;{0}&apos; could not be created: {1}.
        /// </summary>
        internal static string TargetDirectoryCouldNotBeCreated {
            get {
                return ResourceManager.GetString("TargetDirectoryCouldNotBeCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown report type &apos;{0}&apos;..
        /// </summary>
        internal static string UnknownReportType {
            get {
                return ResourceManager.GetString("UnknownReportType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown verbosity level..
        /// </summary>
        internal static string UnknownVerbosityLevel {
            get {
                return ResourceManager.GetString("UnknownVerbosityLevel", resourceCulture);
            }
        }
    }
}
