//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Palmmedia.ReportGenerator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Help {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Help() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Palmmedia.ReportGenerator.Properties.Help", typeof(Help).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default values:.
        /// </summary>
        internal static string DefaultValues {
            get {
                return ResourceManager.GetString("DefaultValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examples:.
        /// </summary>
        internal static string Examples {
            get {
                return ResourceManager.GetString("Examples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explanations:.
        /// </summary>
        internal static string Explanations {
            get {
                return ResourceManager.GetString("Explanations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports: The coverage reports that should be parsed (separated by semicolon). Wildcards are allowed..
        /// </summary>
        internal static string Explanations1 {
            get {
                return ResourceManager.GetString("Explanations1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Filters:     Optional list of files that should be included or excluded in the report..
        /// </summary>
        internal static string Explanations10 {
            get {
                return ResourceManager.GetString("Explanations10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                   Exclusion filters take precedence over inclusion filters. Wildcards are allowed..
        /// </summary>
        internal static string Explanations11 {
            get {
                return ResourceManager.GetString("Explanations11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbosity: The verbosity level of the log messages..
        /// </summary>
        internal static string Explanations12 {
            get {
                return ResourceManager.GetString("Explanations12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target directory: The directory where the generated report should be saved..
        /// </summary>
        internal static string Explanations2 {
            get {
                return ResourceManager.GetString("Explanations2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporttypes: The output formats and scope (separated by semicolon)..
        /// </summary>
        internal static string Explanations3 {
            get {
                return ResourceManager.GetString("Explanations3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source directories: Optional directories which contain the corresponding source code (separated by semicolon)..
        /// </summary>
        internal static string Explanations4 {
            get {
                return ResourceManager.GetString("Explanations4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                     The source files are used if coverage report contains classes without path information..
        /// </summary>
        internal static string Explanations5 {
            get {
                return ResourceManager.GetString("Explanations5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History directory: Optional directory for storing persistent coverage information..
        /// </summary>
        internal static string Explanations6 {
            get {
                return ResourceManager.GetString("Explanations6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                    Can be used in future reports to show coverage evolution..
        /// </summary>
        internal static string Explanations7 {
            get {
                return ResourceManager.GetString("Explanations7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly Filters: Optional list of assemblies that should be included or excluded in the report..
        /// </summary>
        internal static string Explanations8 {
            get {
                return ResourceManager.GetString("Explanations8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Filters:    Optional list of classes that should be included or excluded in the report..
        /// </summary>
        internal static string Explanations9 {
            get {
                return ResourceManager.GetString("Explanations9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters:.
        /// </summary>
        internal static string Parameters {
            get {
                return ResourceManager.GetString("Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [&quot;]-reports:&lt;report&gt;[;&lt;report&gt;][;&lt;report&gt;][&quot;].
        /// </summary>
        internal static string Parameters1 {
            get {
                return ResourceManager.GetString("Parameters1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [&quot;]-targetdir:&lt;target directory&gt;[&quot;].
        /// </summary>
        internal static string Parameters2 {
            get {
                return ResourceManager.GetString("Parameters2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [[&quot;]-reporttypes:&lt;{0}&gt;[;&lt;{0}&gt;][&quot;]]&quot;.
        /// </summary>
        internal static string Parameters3 {
            get {
                return ResourceManager.GetString("Parameters3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [[&quot;]-sourcedirs:&lt;directory&gt;[;&lt;directory&gt;][;&lt;directory&gt;][&quot;]].
        /// </summary>
        internal static string Parameters4 {
            get {
                return ResourceManager.GetString("Parameters4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [[&quot;]-historydir:&lt;history directory&gt;[&quot;]].
        /// </summary>
        internal static string Parameters5 {
            get {
                return ResourceManager.GetString("Parameters5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [[&quot;]-assemblyfilters:&lt;(+|-)filter&gt;[;&lt;(+|-)filter&gt;][;&lt;(+|-)filter&gt;][&quot;]].
        /// </summary>
        internal static string Parameters6 {
            get {
                return ResourceManager.GetString("Parameters6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [[&quot;]-classfilters:&lt;(+|-)filter&gt;[;&lt;(+|-)filter&gt;][;&lt;(+|-)filter&gt;][&quot;]].
        /// </summary>
        internal static string Parameters7 {
            get {
                return ResourceManager.GetString("Parameters7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [[&quot;]-filefilters:&lt;(+|-)filter&gt;[;&lt;(+|-)filter&gt;][;&lt;(+|-)filter&gt;][&quot;]].
        /// </summary>
        internal static string Parameters8 {
            get {
                return ResourceManager.GetString("Parameters8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [[&quot;]-verbosity:&lt;{0}&gt;[&quot;]].
        /// </summary>
        internal static string Parameters9 {
            get {
                return ResourceManager.GetString("Parameters9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to              Values: {0}.
        /// </summary>
        internal static string ReportTypeValues {
            get {
                return ResourceManager.GetString("ReportTypeValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to            Values: {0}.
        /// </summary>
        internal static string VerbosityValues {
            get {
                return ResourceManager.GetString("VerbosityValues", resourceCulture);
            }
        }
    }
}
