using System.Threading.Tasks;
using Microsoft.Testing.Platform.Extensions;

namespace Palmmedia.ReportGenerator.Mtp
{
    internal class ReportGeneratorExtension : IExtension
    {
        public string Uid => nameof(ReportGeneratorCommandLineOptions);

        public string Version => typeof(ReportGeneratorExtension).Assembly.GetName().Version?.ToString() ?? "1.0.0";

        public string DisplayName => "ReportGenerator";

        public string Description => "ReportGenerator converts coverage reports generated by coverlet, OpenCover, dotCover, Visual Studio, NCover, Cobertura, JaCoCo, Clover, gcov, or lcov into human readable reports in various formats.";

        public Task<bool> IsEnabledAsync() => Task.FromResult(true);
    }
}
